name: pro-science
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyterlab
  - ipykernel
  - scikit-learn
  - statsmodels
  - sympy
  - numba
  - cvxpy
  - yfinance
  - pandas-datareader
  - pytest
  - black
  - setuptools
  - wheel
  - pip
  - pip:
      - linearmodels
      - arch
      - torch
      - torchvision
      - tensorflow-macos
      - tensorflow-metal
